version: "2"

run:
  timeout: 10m

linters:
  default: standard
  enable:
    - bodyclose
    - forcetypeassert
    - gocritic
    - govet
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unused
  settings:
    misspell:
      locale: US
    govet:
      disable:
        - fieldalignment
        - shadow
    staticcheck:
      checks: ["all", "-S1*", "-ST1*", "-SA5011", "-SA1019", "-SA2002"]
    revive:
      rules:
        - name: exported
          disabled: true
